version: '3'
services:
  postgres:
    image: postgres:9.4
    networks:
      - impala-nw
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  hadoop-nm:
    image: apache-impala:latest
    hostname: hadoop-nm
    networks:
      - impala-nw
    ports:
      # HDFS
      - 9000
      - 50070
      - 50075
      - 8020
      - 8042
    command: ["hadoop-nm"]
  hive-metastore:
    image: apache-impala:latest
    hostname: hive-metastore
    networks:
      - impala-nw
    external_links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGPASSWORD: postgres
    ports:
      # Hive
      - 9083:9083
    command: ["hive-metastore"]
  impala-state-store:
    image: apache-impala:latest
    hostname: impala-state-store
    networks:
      - impala-nw
    depends_on:
      - hive-metastore
    ports:
      # Impala
      - 21000
      - 21050
      - 22000
      - 23000
      - 24000
      - 25000
      - 25010
      - 25020
    command: ["impala-state-store"]
    environment:
      - IMPALA_STATE_STORE_HOST=impala-state-store
  impala-catalog:
    image: apache-impala:latest
    hostname: impala-catalog
    networks:
      - impala-nw
    depends_on:
      - impala-state-store
      - hive-metastore
    ports:
      # Impala
      - 21000
      - 23020
      - 21050
      - 25000
      - 25010
      - 25020
      - 26000
    command: ["impala-catalog"]
    environment:
      - IMPALA_CATALOG_HOST=impala-catalog
  impala-server:
    image: apache-impala:latest
    hostname: impala-server
    networks:
      - impala-nw
    depends_on:
      - impala-catalog
      - kudu-master-1
      - kudu-master-2
      - kudu-master-3
    ports:
      # Impala
      - 21000
      - 21050
      - 22000
      - 23000
      - 24000
      - 25000
      - 25010
      - 25020
      - 26000
    command: ["impala-server"]
    environment:
      - KUDU_MASTERS=kudu-master-1,kudu-master-2,kudu-master-3
    deploy:
      replicas: 3
  kudu-master-1:
    image: apache-kudu:latest
    networks:
      impala-nw:
        aliases:
        - kudu
    hostname: kudu-master-1
    ports:
      - "7051"
      - "8051:8051"
    command: ["master"]
    environment:
      - KUDU_MASTERS=kudu-master-1,kudu-master-2,kudu-master-3
  kudu-master-2:
    image: apache-kudu:latest
    networks:
      impala-nw:
        aliases:
        - kudu
    hostname: kudu-master-2
    ports:
      - "7051"
      - "8051"
    command: ["master"]
    environment:
      - KUDU_MASTERS=kudu-master-1,kudu-master-2,kudu-master-3
  kudu-master-3:
    image: apache-kudu:latest
    networks:
      impala-nw:
        aliases:
          - kudu
    hostname: kudu-master-3
    ports:
      - "7051"
      - "8051"
    command: ["master"]
    environment:
      - KUDU_MASTERS=kudu-master-1,kudu-master-2,kudu-master-3
  kudu-tserver:
    image: apache-kudu:latest
    networks:
      - impala-nw
    depends_on:
      - kudu-master-1
      - kudu-master-2
      - kudu-master-3
    ports:
      - "7050"
      - "8050"
    command: ["tserver"]
    environment:
      - KUDU_MASTERS=kudu-master-1,kudu-master-2,kudu-master-3
    deploy:
      replicas: 3
networks:
  default:
    external:
      name: impala-nw
  impala-nw:
    driver: bridge

